//! Build script for USG SIP Soft Client.
//!
//! On Windows, this embeds:
//! - Application manifest (UAC settings, DPI awareness)
//! - Version information resource
//! - Application icon

fn main() {
    // Only run Windows-specific build steps on Windows target
    #[cfg(target_os = "windows")]
    windows_build();

    // Rerun if these files change
    println!("cargo:rerun-if-changed=app.manifest");
    println!("cargo:rerun-if-changed=resources/app-icon.ico");
    println!("cargo:rerun-if-changed=build.rs");
}

#[cfg(target_os = "windows")]
fn windows_build() {
    use std::env;
    use std::fs;
    use std::path::Path;

    // Get version from Cargo.toml
    let version = env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.1.0".to_string());
    let version_parts: Vec<&str> = version.split('.').collect();
    let major = version_parts.first().unwrap_or(&"0");
    let minor = version_parts.get(1).unwrap_or(&"1");
    let patch = version_parts.get(2).unwrap_or(&"0");

    // Create version info resource
    let rc_content = format!(
        r#"// Windows resource file - auto-generated by build.rs
#include <windows.h>

// Version information
VS_VERSION_INFO VERSIONINFO
FILEVERSION {major},{minor},{patch},0
PRODUCTVERSION {major},{minor},{patch},0
FILEFLAGSMASK VS_FFI_FILEFLAGSMASK
FILEFLAGS 0
FILEOS VOS_NT_WINDOWS32
FILETYPE VFT_APP
FILESUBTYPE VFT2_UNKNOWN
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904B0"
        BEGIN
            VALUE "CompanyName", "USG Communications"
            VALUE "FileDescription", "USG SIP Soft Client - Secure VoIP Communications"
            VALUE "FileVersion", "{version}"
            VALUE "InternalName", "sip-softclient"
            VALUE "LegalCopyright", "Copyright (C) 2024-2025 USG Communications. All rights reserved."
            VALUE "OriginalFilename", "sip-softclient.exe"
            VALUE "ProductName", "USG SIP Soft Client"
            VALUE "ProductVersion", "{version}"
            VALUE "Comments", "CNSA 2.0 Compliant SIP Soft Client for Enterprise/Government Use"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x0409, 0x04B0
    END
END

// Application manifest
1 RT_MANIFEST "app.manifest"

// Application icon (if exists)
// 1 ICON "resources/app-icon.ico"
"#,
        major = major,
        minor = minor,
        patch = patch,
        version = version
    );

    // Write the resource file
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let rc_path = Path::new(&out_dir).join("app.rc");
    fs::write(&rc_path, rc_content).expect("Failed to write app.rc");

    // Try to compile the resource file if windres is available
    // This requires the Windows SDK or MinGW to be installed
    let windres_result = std::process::Command::new("windres")
        .args([
            rc_path.to_str().expect("Invalid path"),
            "-O",
            "coff",
            "-o",
        ])
        .arg(Path::new(&out_dir).join("app.res"))
        .status();

    match windres_result {
        Ok(status) if status.success() => {
            println!("cargo:rustc-link-arg-bins={}/app.res", out_dir);
        }
        _ => {
            // windres not available, try embed-resource crate approach
            // For now, just print a warning
            println!("cargo:warning=windres not found, Windows resources will not be embedded");
            println!(
                "cargo:warning=Install Windows SDK or MinGW for full Windows resource support"
            );
        }
    }
}
