apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sbc.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sbc.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- include "sbc.config" . | nindent 4 }}
